import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "#7209B7",
        "primary-transparent": "#7209B780",
        blue: "#0055FF",
        green: "#00DA16",
        red: { 100: "#CB0000", 90: "#CF0000" },
        black: {
          100: "#353535",
          75: "#676767",
          50: "#9B9B9B",
          25: "#CDCDCD",
        },
        white: {
          base: "#FFFFFF",
          98: "#FAFAFA",
          97: "#F7F7F8",
        },
        hover: "#550788",
      },
      fontWeight: {
        medium: "500",
        semibold: "600",
        bold: "700",
      },
      fontSize: {
        sm: "15px",
        md: "18px",
        lg: "32px",
      },
    },
    safelist: [
      "text-foreground",
      "text-primary",
      "text-blue",
      "text-green",
      "text-red-100",
      "text-red-90",
      "text-black-100",
      "text-black-75",
      "text-black-50",
      "text-black-25",
      "text-white-base",
      "text-white-98",
      "text-white-97",
      "text-hover",
      "bg-background",
      "bg-foreground",
      "bg-primary",
      "bg-blue",
      "bg-green",
      "bg-red-100",
      "bg-red-90",
      "bg-black-100",
      "bg-black-75",
      "bg-black-50",
      "bg-black-25",
      "bg-white-base",
      "bg-white-98",
      "bg-white-97",
      "bg-hover",
    ],
  },
  plugins: [],
} satisfies Config;
